### ISSUE TITLE
EH with neutrinos

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/cosmoprimo#2]
I'm getting a warning about Eisenstein & Hu not dealing with neutrinos, but I know there is a version that does, because my C++ code uses it... I guess it came from here:
http://background.uchicago.edu/~whu/transfer/power.c
(it also seems like it should be able to figure out sigma8 for itself, without demanding it be set...)

**Comment by adematti** [comment]
Sorry for the delay, being slammed by other developments. 43c3fcd80e0fe341368981a93f5b735dfe2aa273 implements "einsenstein_hu_nowiggle_variants" engine as specified in https://arxiv.org/pdf/astro-ph/9710252.pdf. I implemented it in a different engine than "einsenstein_hu_nowiggle" since equations do not exactly match in the no-neutrino case. It would be nice at some point to come up with the similar neutrino-friendly transfer function with BAO wiggles.

**Comment by pmcdonal** [comment]
Thanks. The no-wiggle version is the only one I use (to help create an isolated-wiggle template that removes the low-k, baryon damping part... which probably doesn't matter, but I like to do it "correctly" so I don't need to worry about it).
